# Basic Config
server.port=3000
spring.application.name=broker-message

# PostgreSQL Config (Step C)
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/retry_db
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# MongoDB Config (Step D - Cloud Atlas)
spring.data.mongodb.uri=mongodb+srv://gonzadev:txN0JLVPv1SSr3FQ@clusterkafka.dyf05gz.mongodb.net/broker_processed_db?retryWrites=true&w=majority

# Kafka Config
spring.kafka.bootstrap-servers=127.0.0.1:9092
spring.kafka.consumer.group-id=broker-message-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Email Config (Step B - Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gonzalo.gb11.ggb@gmail.com
spring.mail.password=zyxxicpexqdzcrop
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Custom Endpoints (Step A)
app.retry.endpoint.payment=http://127.0.0.1:3001/payments
app.retry.endpoint.order=http://127.0.0.1:3002/orders
app.retry.endpoint.product=http://127.0.0.1:3003/products
